### ISSUE TITLE
Potential source for a denial of service attack 

### ISSUE THREAD

**Issue by stewartie4** [0chain/0proxy#1]
I believe I’ve found  potential source for a denial of service attack on 0proxy:

Steps to reproduce:
1. Attempt an upload to the proxy with a non-existent allocation ID
2. The proxy will take a very long time to respond, up to 2 minutes before killing the connection/returning a gateway timeout  
3. If this is done enough (my load tests suggest 15 requests are enough) the proxy will stop taking new valid requests and rerun the following response
![image](https://user-images.githubusercontent.com/18306778/110221150-6d73e880-7ec2-11eb-971c-80900a7a42c4.png)

I understand 0proxy is rate limited which seems to be kicking in but that doesn't resolve the backpressure issue eg. a small number of requests holding up a finite number of resources for a disproportionate amount of time

**Comment by guruhubb** [comment]
We have three 0proxy nodes running and each has a rate limit of 5, so it makes sense that it stops at 15. This can be scaled to n nodes, with much higher rate limits. I don't this as an issue because a dApp will be running this locally.  I'll ask devops to double the rate limits and add another node to demonstrate this.

**Comment by anish-squareops** [comment]
I have increased the rate limit to 10 and added another node.

**Comment by shravanshetty1** [comment]
I tried sending non existent allocation id to the proxy and it returned in around 700 ms, here is the curl
```
curl --request POST \
  --url https://one.devnet-0chain.net/proxy/upload \
  --header 'accept: application/json, text/plain, */*' \
  --header 'accept-language: en-US,en;q=0.9' \
  --header 'authority: one.devnet-0chain.net' \
  --header 'cache-control: no-cache' \
  --header 'content-type: multipart/form-data; boundary=---011000010111000001101001' \
  --header 'origin: https://one.devnet-0chain.net' \
  --header 'pragma: no-cache' \
  --header 'referer: https://one.devnet-0chain.net/0box/files/upload' \
  --header 'sec-ch-ua: "Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"' \
  --header 'sec-ch-ua-mobile: ?0' \
  --header 'sec-fetch-dest: empty' \
  --header 'sec-fetch-mode: cors' \
  --header 'sec-fetch-site: same-origin' \
  --header 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36' \
  --form 'client_json={"client_id":"650f5ab5ef398e98dc0ead026f6721f68723f59085590d6f9d20c2a343bed915","client_key":"b5cc2ace87d1d063d4419f3ef6d11c5356a01afe1d2b27f60e7707f5fd50db12758eec9bd20bc440d19b26d656b0b367b8ee9cd5b54549cb6d02340fa81e6218","keys":[{"public_key":"b5cc2ace87d1d063d4419f3ef6d11c5356a01afe1d2b27f60e7707f5fd50db12758eec9bd20bc440d19b26d656b0b367b8ee9cd5b54549cb6d02340fa81e6218","private_key":"b73e782924fd24dfa108e8ab28875c76a6bbc4b1425e59f1b68b906171e4c41e"}],"mnemonics":"attend inspire hip egg disease endorse twice mixture mistake coast clay wisdom raccoon bachelor hour initial misery tonight input theory present dwarf fish average","version":"1.0","date_created":"53165-07-19 18:16:22"}' \
  --form allocation=something \
  --form 'remote_path=/Ch24_nonPBR@Roundhouse Kick.fbx' \
  --form 'file=@C:\Users\shrav\Downloads\Ch24_nonPBR@Roundhouse Kick.fbx'
```

There could have been some kind of performance issue while you were testing. However I agree that we should not keep request alive for 2 minutes - the blockchain should timeout request after 10 seconds.

This should resolve any kind of connection limit attacks that can be caused when connection is not closed. Will track this issue in the 0chain repo.
https://github.com/0chain/0chain/issues/108

**Comment by stewartie4** [comment]
@shravanshetty1 That sounds like a solution for the proxy, rather than masking the problem eg. by adding capacity.

I think i've found a possible root cause of the problem which is a lot more concerning.
The blobber /referencepath/<allocation_id> endpoint, which the proxy calls during the process of committing an upload will hang indefinitely if the file path does not start with a slash and 60s if the allocation cannot be found.
I believe this to be a serious threat to the network as a bad actor could hang up all the server threads of a given blobber very easily resulting in a denial of service to other users.

I say indefinitely for the file path issue as i have been running a request for the past 10 minutes and have not got a response yet. I will post if i get one.

See the gifs attached.

![blober_reference_path_bad_dir](https://user-images.githubusercontent.com/18306778/111001429-a953f580-837b-11eb-8f6d-4339a91ba5ac.gif)
![blobber_reference_path_bad_allocation](https://user-images.githubusercontent.com/18306778/111001660-1c5d6c00-837c-11eb-9afc-1d0dd5a2d22d.gif)

**Comment by shravanshetty1** [comment]
Added these issues which should fix the above
https://github.com/0chain/blobber/issues/31
https://github.com/0chain/0chain/issues/108

**Comment by guruhubb** [comment]
This is a blobber issue, since the allocation is already done on the chain. @shravanshetty1 you need to have blobber allow non-slash path, and take care of the bad path condition.

**Comment by Sriep** [comment]
https://github.com/0chain/blobber/pull/50 has been merged. Can test to see if this fixes the issue.

**Comment by stewartie4** [comment]
Thanks,
Have tested and can confirm this is no longer an issue.
